spring:
  application:
    name: springcloud-demo-ping

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springcloud.feign.MessageClient: DEBUG