spring:
  application:
    name: springcloud-demo-eureka
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    #preferIpAddress: true
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/

---
spring:
  application:
    name: springcloud-demo-eureka
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    #preferIpAddress: true
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

